version: '3.8'

services:
  app:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces/${localWorkspaceFolderBasename}:cached
      - openplayground-config:/home/vscode/.config
    command: sleep infinity
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - XDG_CONFIG_HOME=/home/vscode/.config
    network_mode: host

volumes:
  openplayground-config:
